@{
    AliasesToExport      = @('cfhtml', 'Close-HtmlSession', 'ConvertFrom-HtmlClass', 'ConvertFrom-HtmlTag', 'ConvertFrom-HtmlLinkedJSEndpoint', 'ConvertFrom-HtmlReactFlight', 'ConvertFrom-HtmlReactFlightPayload', 'ConvertFrom-JSAst', 'ConvertFrom-JSEndpoint', 'Export-HtmlSession', 'Format-JS', 'Get-HtmlConsoleLog', 'Get-HtmlContent', 'Get-HtmlCookie', 'Get-HtmlFormField', 'Get-HtmlInteractable', 'Get-HtmlLoginForm', 'Get-HtmlNetworkLog', 'Import-HtmlSession', 'Invoke-HtmlClick', 'Invoke-HtmlDomScript', 'Invoke-HtmlLogin', 'Invoke-HtmlNavigation', 'Invoke-HtmlScript', 'Invoke-HtmlAutoSubmitForm', 'Measure-HtmlDocument', 'Measure-HtmlPerformance', 'New-HtmlCookie', 'Open-HtmlSession', 'Save-HtmlAttachment', 'Save-HtmlDownload', 'Save-HtmlHar', 'Save-HtmlPdf', 'Save-HtmlScreenshot', 'Select-HtmlJSConfig', 'Select-HtmlJSVariable', 'Select-JavaScriptDescendantNode', 'Select-JSAstNode', 'Select-JSDescendantNode', 'Set-HtmlChecked', 'Set-HtmlCookie', 'Set-HtmlHttpClientOption', 'Set-HtmlInput', 'Set-HtmlSelectOption', 'Show-HtmlHar', 'sjsdn', 'sjsn', 'sjsv', 'Start-HtmlSession', 'Start-HtmlTracing', 'Start-HtmlVideoRecording', 'Stop-HtmlSession', 'Stop-HtmlTracing', 'Stop-HtmlVideoRecording', 'Submit-HtmlForm')
    Author               = 'Przemyslaw Klys'
    CmdletsToExport      = @('Clear-HtmlBrowserCache', 'Close-HtmlBrowserSession', 'Compare-Html', 'Compare-HtmlStaticRendered', 'Convert-HtmlToMarkdown', 'Convert-HtmlToText', 'ConvertFrom-CssUrl', 'ConvertFrom-Html', 'ConvertFrom-HtmlAppState', 'ConvertFrom-HtmlAttributes', 'ConvertFrom-HtmlCookie', 'ConvertFrom-HtmlEntity', 'ConvertFrom-HtmlForm', 'ConvertFrom-HtmlHeadLink', 'ConvertFrom-HtmlImageCandidate', 'ConvertFrom-HtmlJsonLd', 'ConvertFrom-HtmlLinkedJavaScriptEndpoint', 'ConvertFrom-HtmlLink', 'ConvertFrom-HtmlList', 'ConvertFrom-HtmlMeta', 'ConvertFrom-HtmlMicrodata', 'ConvertFrom-HtmlOpenGraph', 'ConvertFrom-HtmlRscPayload', 'ConvertFrom-HtmlScriptData', 'ConvertFrom-HtmlSitemap', 'ConvertFrom-HtmlSyndication', 'ConvertFrom-HtmlTable', 'ConvertFrom-JavaScriptAst', 'ConvertFrom-JavaScriptEndpoint', 'ConvertFrom-RobotsTxt', 'ConvertFrom-WebManifest', 'ConvertFrom-WellKnownText', 'ConvertTo-HtmlDatasetJsonL', 'ConvertTo-HtmlEntity', 'Export-BrowserState', 'Export-HtmlBrowserSession', 'Export-HtmlOutline', 'Find-HtmlApiEndpoint', 'Find-HtmlInteractionSurface', 'Format-Css', 'Format-Html', 'Format-JavaScript', 'Get-CssVariable', 'Get-HtmlBrowserConsoleLog', 'Get-HtmlBrowserContent', 'Get-HtmlBrowserCookie', 'Get-HtmlBrowserFormField', 'Get-HtmlBrowserInteractable', 'Get-HtmlBrowserLoginForm', 'Get-HtmlBrowserNetworkLog', 'Get-HtmlCrawlProfile', 'Get-HtmlExtractionProfile', 'Get-HtmlResource', 'Import-BrowserState', 'Import-HtmlBrowserSession', 'Invoke-HtmlBrowserClick', 'Invoke-HtmlBrowserDomScript', 'Invoke-HtmlBrowserLogin', 'Invoke-HtmlBrowserNavigation', 'Invoke-HtmlBrowserScript', 'Invoke-HtmlCrawl', 'Invoke-HtmlRendering', 'Invoke-HtmlFormRelay', 'Invoke-HtmlPageWorkbench', 'Measure-CssSpecificity', 'Measure-HtmlBrowserPerformance', 'Measure-HtmlCompatibility', 'Measure-HtmlDocumentStructure', 'New-HtmlBrowserCookie', 'Optimize-Css', 'Optimize-Email', 'Optimize-Html', 'Optimize-JavaScript', 'Register-HtmlRoute', 'Save-HtmlBrowserAttachment', 'Save-HtmlBrowserHar', 'Save-HtmlBrowserPdf', 'Save-HtmlBrowserScreenshot', 'Select-CssDeclaration', 'Select-CssRule', 'Select-HtmlAsset', 'Select-HtmlAttributeValue', 'Select-HtmlData', 'Select-HtmlInnerText', 'Select-HtmlJavaScriptConfig', 'Select-HtmlJavaScriptVariable', 'Select-HtmlNode', 'Select-HtmlScript', 'Select-HtmlStyleUsage', 'Select-HtmlToken', 'Select-JavaScriptAstNode', 'Select-JavaScriptVariable', 'Set-HtmlBrowserChecked', 'Set-HtmlBrowserClientOption', 'Set-HtmlBrowserCookie', 'Set-HtmlBrowserInput', 'Set-HtmlBrowserSelectOption', 'Show-HtmlBrowserHar', 'Start-HtmlBrowserTracing', 'Start-HtmlBrowserVideoCapture', 'Stop-HtmlBrowserTracing', 'Stop-HtmlBrowserVideoCapture', 'Submit-HtmlBrowserForm', 'Test-HtmlBrowser', 'Test-HtmlExtractionPlan', 'Test-HtmlMicrodata', 'Unregister-HtmlRoute')
    CompanyName          = 'Evotec'
    CompatiblePSEditions = @('Desktop', 'Core')
    Copyright            = '(c) 2011 - 2026 Przemyslaw Klys @ Evotec. All rights reserved.'
    Description          = 'Module that allows to manipulate, parse, format and optimize HTML, JavaScript and CSS'
    FunctionsToExport    = @()
    GUID                 = 'f0387960-7034-4918-a1e1-d5847cbf90df'
    ModuleVersion        = '2.0.16'
    PowerShellVersion    = '5.1'
    PrivateData          = @{
        PSData = @{
            ExternalModuleDependencies = @()
            IconUri                    = 'https://evotec.xyz/wp-content/uploads/2018/12/PSWriteHTML.png'
            ProjectUri                 = 'https://github.com/EvotecIT/PSParseHTML'
            RequireLicenseAcceptance   = $false
            Tags                       = @('HTML', 'WWW', 'JavaScript', 'CSS', 'Windows', 'MacOS', 'Linux')
        }
    }
    RequiredModules      = @()
    RootModule           = 'PSParseHTML.psm1'
    ScriptsToProcess     = @()
}
